[phases.build]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "java -jar backend/target/backend-1.0.0.jar --spring.profiles.active=prod --server.port=$PORT"
