[phases.build]
nixPkgs = ["jdk17", "maven"]

[phases.install]
cmds = ["cd backend && mvn clean package -DskipTests"]

[start]
cmd = "java -Dspring.profiles.active=prod -Dserver.port=$PORT -jar backend/target/backend-1.0.0.jar"
